name: Build, test, lint

on: [ push ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: Install dependencies
        run: |
            npm install
            npm install -g truffle
            npm install -g ganache-cli
            npm install -g eslint
      - name: Run truffle tests and coverage
        run: |
            ganache-cli > /dev/null &
            truffle run coverage
            eslint .