name: Test contracts

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: Install dependecies
        run: |
            npm install
            npm install -g truffle
            npm install -g ganache-cli
            ganache-cli &
            truffle test test/contracts